# autoPhotoEdit -- automatic post-production for Sony RAW files.
# SPDX-License-Identifier: GPL-3.0-or-later
"""Test 19 of section 13, second half: the manifest, the worker, and the shell.

Three things are checked, and the third is the one with teeth.

The **manifest** has to satisfy the installability criteria, or the "Installa
come app" button of section 21.2 is a button that does nothing: icons at 192 and
512, ``display: standalone``, and a ``start_url`` inside ``scope``.

The **service worker** must not intercept ``/api`` or ``/ws``. It is checked on
the built worker rather than on the source, because what ships is what matters,
and on the precache list, which is generated: a build that started precaching
API responses would show it there first.

And the **freshness** it exists to protect: two reads of one endpoint, with the
server changed in between, give different answers. That is the property section
4 is really asking for -- a cache that lies about the catalogue is worse than no
cache -- and it is checked against the running application, where the SPA
fallback is also in a position to break it by answering ``/api`` with HTML.

Everything that needs a build skips without one: ``backend/ape/static`` is
generated by ``npm run build`` and is not in the repository (section 18.3).
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from ape.api.app import create_app
from ape.api.spa import STATIC_DIR, build_present, mount_frontend

pytestmark = pytest.mark.skipif(
    not build_present(), reason="nessuna build del frontend in backend/ape/static (npm run build)"
)


def _manifest() -> dict:
    return json.loads((STATIC_DIR / "manifest.webmanifest").read_text(encoding="utf-8"))


def test_the_manifest_meets_the_installability_criteria():
    manifest = _manifest()
    assert manifest["display"] == "standalone"
    assert manifest["scope"] == "/"
    assert manifest["start_url"].startswith(manifest["scope"])
    assert manifest["id"]
    assert manifest["lang"] == "it"
    assert manifest["name"] and manifest["description"]

    sizes = {icon["sizes"] for icon in manifest["icons"]}
    assert "192x192" in sizes and "512x512" in sizes
    purposes = {icon.get("purpose", "any") for icon in manifest["icons"]}
    assert "maskable" in purposes

    for icon in manifest["icons"]:
        path = STATIC_DIR / icon["src"].lstrip("/")
        assert path.is_file(), f"icona dichiarata e assente: {icon['src']}"


def test_the_theme_is_neutral_grey():
    """Section 10: no saturated colour anywhere near the photographs."""
    manifest = _manifest()
    for key in ("theme_color", "background_color"):
        red, green, blue = (int(manifest[key][index : index + 2], 16) for index in (1, 3, 5))
        assert max(red, green, blue) - min(red, green, blue) <= 8, key


def test_the_service_worker_never_touches_the_api_or_the_socket():
    worker = (STATIC_DIR / "sw.js").read_text(encoding="utf-8")

    # The guard itself, on the built file.
    assert "/api/" in worker and "/ws" in worker
    assert "isLiveData" in worker or "startsWith" in worker

    # And the generated precache list, which is where a mistake would land.
    precached = [entry["url"] for entry in _precache_entries(worker)]
    assert precached, "il worker non precarica nulla: la app shell manca"
    for url in precached:
        assert not url.startswith("api"), url
        assert not url.startswith("/api"), url
        assert "/ws" not in url, url
        # Photographs are megabytes each and are never part of the shell.
        assert not url.endswith((".jpg", ".jpeg")), url


def _precache_entries(worker: str) -> list[dict]:
    """The list injected in place of ``self.__WB_MANIFEST``."""
    start = worker.index("[{", worker.index("precache") if "precache" in worker else 0)
    depth = 0
    for index in range(start, len(worker)):
        if worker[index] == "[":
            depth += 1
        elif worker[index] == "]":
            depth -= 1
            if depth == 0:
                return json.loads(worker[start : index + 1])
    raise AssertionError("lista di precache non trovata nel service worker")


def test_the_shell_is_served_and_the_router_owns_the_urls(catalog):
    with TestClient(create_app(start_workers=False), base_url="http://127.0.0.1") as client:
        root = client.get("/")
        assert root.status_code == 200
        assert "text/html" in root.headers["content-type"]
        # A reload deep in the application gives the same document: there is no
        # file at that path and no address bar to correct it with (section 21.2).
        deep = client.get("/progetti/3/foto")
        assert deep.status_code == 200
        assert deep.text == root.text
        assert "no-store" in root.headers["cache-control"]

        manifest = client.get("/manifest.webmanifest")
        assert manifest.status_code == 200
        assert "manifest" in manifest.headers["content-type"]

        # Hashed assets, on the other hand, can be cached for ever.
        asset = next((STATIC_DIR / "assets").glob("*.js"))
        response = client.get(f"/assets/{asset.name}")
        assert response.status_code == 200
        assert "immutable" in response.headers["cache-control"]


def test_an_unknown_api_path_is_a_404_not_the_shell(catalog):
    """The catch-all must never answer for the API, or every 404 becomes HTML."""
    with TestClient(create_app(start_workers=False), base_url="http://127.0.0.1") as client:
        response = client.get("/api/questo-non-esiste")
        assert response.status_code == 404
        assert "<!doctype html" not in response.text.lower()


def test_two_reads_of_one_endpoint_see_the_change_between_them(catalog, card: Path):
    """The freshness the worker is forbidden from breaking (test 19)."""
    with TestClient(create_app(start_workers=False), base_url="http://127.0.0.1") as client:
        assert client.get("/api/projects").json() == []
        created = client.post(
            "/api/projects", json={"name": "Vacanza", "source_dir": str(card)}
        )
        assert created.status_code == 201
        second = client.get("/api/projects").json()
        assert len(second) == 1
        # And nothing in the response invites a cache to keep it.
        headers = client.get("/api/projects").headers
        assert "max-age" not in headers.get("cache-control", "")


def test_mounting_is_skipped_when_there_is_no_build(tmp_path):
    from fastapi import FastAPI

    assert mount_frontend(FastAPI(), tmp_path) is False
